#file: noinspection SpringBootApplicationYaml
spring:
  application:
    name: Backend
  config:
    import:
      - classpath:application-db.yaml
      - classpath:application-jwt.yaml
  server:
    port: 8080
    address: 0.0.0.0
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
#  autoconfigure:
    #exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace